jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # build exe ...
      - uses: softprops/action-gh-release@v2
        with:
          files: "*.exe"
